import type { Lead, SearchResult, ContactEvent, Note, DashboardStats, StatusCount } from "@/types"

export const MOCK_SEARCH_RESULTS: SearchResult[] = [
  {
    externalId: "gp_001",
    businessName: "Austin Tile & Stone Works",
    address: "4521 Burnet Rd",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0142",
    hasWebsite: false,
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_002",
    businessName: "Lone Star Landscaping Co",
    address: "1802 S Lamar Blvd",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0287",
    email: "info@lonestarlandscaping.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_003",
    businessName: "Hill Country HVAC Solutions",
    address: "3200 Bee Cave Rd Ste 100",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0391",
    email: "service@hillcountryhvac.com",
    website: "https://hillcountryhvac.com",
    hasWebsite: true,
    closeabilityScore: 50,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_004",
    businessName: "Capitol City Plumbing",
    address: "711 Congress Ave",
    city: "Austin",
    state: "TX",
    hasWebsite: false,
    closeabilityScore: 20,
    scoreBreakdown: { noWebsite: 40, hasPhone: 0, hasEmail: 0, bothContacts: 0, noContacts: -20 },
  },
  {
    externalId: "gp_005",
    businessName: "Bluebird Electric LLC",
    address: "9801 N Lamar Blvd",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0456",
    email: "jobs@bluebirdelectric.net",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_006",
    businessName: "Cedar Park Auto Repair",
    address: "500 E Whitestone Blvd",
    city: "Cedar Park",
    state: "TX",
    phone: "(512) 555-0523",
    website: "https://cedarparkautoshop.com",
    hasWebsite: true,
    closeabilityScore: 20,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_007",
    businessName: "Luxe Salon & Spa",
    address: "2222 Rio Grande St",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0614",
    email: "hello@luxesalonspa.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_008",
    businessName: "Magnolia Roofing & Gutters",
    address: "14200 N Interstate 35",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0789",
    hasWebsite: false,
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_009",
    businessName: "Alamo Signs & Graphics",
    address: "6800 Alamo Pkwy",
    city: "San Antonio",
    state: "TX",
    phone: "(210) 555-0812",
    email: "sales@alamosigns.com",
    website: "https://alamosigns.com",
    hasWebsite: true,
    closeabilityScore: 50,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_010",
    businessName: "Brisket & Beans BBQ",
    address: "4501 San Jacinto St",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-0923",
    email: "orders@brisketandbeans.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_011",
    businessName: "Texas Tree Service",
    address: "2150 S Congress Ave",
    city: "Austin",
    state: "TX",
    hasWebsite: false,
    closeabilityScore: 20,
    scoreBreakdown: { noWebsite: 40, hasPhone: 0, hasEmail: 0, bothContacts: 0, noContacts: -20 },
  },
  {
    externalId: "gp_012",
    businessName: "River Oaks Cleaning Co",
    address: "1919 Westheimer Rd",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-1124",
    email: "info@riveroakscleaning.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_013",
    businessName: "Sunset Pool Service",
    address: "8800 Manchaca Rd",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-1235",
    hasWebsite: false,
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_014",
    businessName: "Iron Horse Welding & Fab",
    address: "7700 E Ben White Blvd",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-1389",
    hasWebsite: false,
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_015",
    businessName: "Pecos Pest Control",
    address: "1500 E Cesar Chavez St",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-1467",
    email: "service@pecospest.com",
    website: "https://pecospest.com",
    hasWebsite: true,
    closeabilityScore: 50,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_016",
    businessName: "Six Shooter Fencing Co",
    address: "3301 W Anderson Ln",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-1578",
    email: "quotes@sixshooterfencing.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_017",
    businessName: "Texas Star Painting",
    address: "9001 N Mopac Expy",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-1623",
    hasWebsite: false,
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_018",
    businessName: "Gulf Coast Concrete & Masonry",
    address: "4400 W Gray St",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-1745",
    email: "bids@gulfcoastconcrete.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
  {
    externalId: "gp_019",
    businessName: "Mesa Verde Landscaping",
    address: "5600 N New Braunfels Ave",
    city: "San Antonio",
    state: "TX",
    phone: "(210) 555-1892",
    website: "https://mesaverdescape.com",
    hasWebsite: true,
    closeabilityScore: 20,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
  },
  {
    externalId: "gp_020",
    businessName: "Alamo City Auto Glass",
    address: "2800 NE Loop 410",
    city: "San Antonio",
    state: "TX",
    phone: "(210) 555-1967",
    email: "repair@alamocityglass.com",
    hasWebsite: false,
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
  },
]

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString()
const daysFromNow = (d: number) => new Date(now + d * 86400000).toISOString()

export const MOCK_SAVED_LEADS: Lead[] = [
  {
    id: "lead_001",
    businessName: "Lone Star Landscaping Co",
    address: "1802 S Lamar Blvd",
    city: "Austin",
    state: "TX",
    zip: "78704",
    phone: "(512) 555-0287",
    email: "info@lonestarlandscaping.com",
    hasWebsite: false,
    googlePlaceId: "gp_002",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "INTERESTED",
    lastContactedAt: daysAgo(3),
    nextFollowUpAt: daysFromNow(4),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
    contactEvents: [
      {
        id: "ce_001",
        leadId: "lead_001",
        type: "CALL",
        notes: "Spoke with owner Mike. Very interested in getting a website.",
        outcome: "Sending proposal",
        createdAt: daysAgo(3),
      },
      {
        id: "ce_002",
        leadId: "lead_001",
        type: "EMAIL",
        notes: "Sent proposal for $2,400 landscaping website package.",
        outcome: "Awaiting response",
        createdAt: daysAgo(2),
      },
    ],
    notes: [
      {
        id: "note_001",
        leadId: "lead_001",
        content: "Owner is Mike Torres. Best time to call is 7–9am before crews go out. Been in business 12 years.",
        createdAt: daysAgo(14),
        updatedAt: daysAgo(14),
      },
    ],
  },
  {
    id: "lead_002",
    businessName: "Bluebird Electric LLC",
    address: "9801 N Lamar Blvd",
    city: "Austin",
    state: "TX",
    zip: "78753",
    phone: "(512) 555-0456",
    email: "jobs@bluebirdelectric.net",
    hasWebsite: false,
    googlePlaceId: "gp_005",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "FOLLOW_UP",
    lastContactedAt: daysAgo(7),
    nextFollowUpAt: daysFromNow(1),
    createdAt: daysAgo(21),
    updatedAt: daysAgo(7),
    contactEvents: [
      {
        id: "ce_003",
        leadId: "lead_002",
        type: "CALL",
        notes: "Left voicemail with owner.",
        outcome: "No answer",
        createdAt: daysAgo(10),
      },
      {
        id: "ce_004",
        leadId: "lead_002",
        type: "EMAIL",
        notes: "Sent cold email introducing my services.",
        outcome: "Replied — call back next week",
        createdAt: daysAgo(7),
      },
    ],
    notes: [
      {
        id: "note_002",
        leadId: "lead_002",
        content: "Owner said they've been meaning to get a site but too busy. Follow up early morning.",
        createdAt: daysAgo(7),
        updatedAt: daysAgo(7),
      },
    ],
  },
  {
    id: "lead_003",
    businessName: "Six Shooter Fencing Co",
    address: "3301 W Anderson Ln",
    city: "Austin",
    state: "TX",
    zip: "78757",
    phone: "(512) 555-1578",
    email: "quotes@sixshooterfencing.com",
    hasWebsite: false,
    googlePlaceId: "gp_016",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "CONTACTED",
    lastContactedAt: daysAgo(5),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(5),
    contactEvents: [
      {
        id: "ce_005",
        leadId: "lead_003",
        type: "CALL",
        notes: "Spoke briefly. Owner was on a job, asked to call back Friday.",
        outcome: "Call back Friday",
        createdAt: daysAgo(5),
      },
    ],
    notes: [],
  },
  {
    id: "lead_004",
    businessName: "Gulf Coast Concrete & Masonry",
    address: "4400 W Gray St",
    city: "Houston",
    state: "TX",
    zip: "77019",
    phone: "(713) 555-1745",
    email: "bids@gulfcoastconcrete.com",
    hasWebsite: false,
    googlePlaceId: "gp_018",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "WON",
    lastContactedAt: daysAgo(30),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(30),
    contactEvents: [
      {
        id: "ce_006",
        leadId: "lead_004",
        type: "CALL",
        notes: "Initial contact. Owner immediately interested.",
        outcome: "Interested",
        createdAt: daysAgo(44),
      },
      {
        id: "ce_007",
        leadId: "lead_004",
        type: "MEETING",
        notes: "Video call to review scope. Agreed on $3,200 package.",
        outcome: "Closed — $3,200",
        createdAt: daysAgo(40),
      },
    ],
    notes: [
      {
        id: "note_003",
        leadId: "lead_004",
        content: "Closed at $3,200 for a 5-page site + contact form. Paid 50% deposit.",
        createdAt: daysAgo(40),
        updatedAt: daysAgo(40),
      },
    ],
  },
  {
    id: "lead_005",
    businessName: "Hill Country HVAC Solutions",
    address: "3200 Bee Cave Rd Ste 100",
    city: "Austin",
    state: "TX",
    zip: "78746",
    phone: "(512) 555-0391",
    email: "service@hillcountryhvac.com",
    website: "https://hillcountryhvac.com",
    hasWebsite: true,
    googlePlaceId: "gp_003",
    closeabilityScore: 50,
    scoreBreakdown: { noWebsite: 0, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "NOT_INTERESTED",
    lastContactedAt: daysAgo(20),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(20),
    contactEvents: [
      {
        id: "ce_008",
        leadId: "lead_005",
        type: "CALL",
        notes: "Owner happy with current website. Not interested in redesign.",
        outcome: "Not interested",
        createdAt: daysAgo(20),
      },
    ],
    notes: [],
  },
  {
    id: "lead_006",
    businessName: "Alamo City Auto Glass",
    address: "2800 NE Loop 410",
    city: "San Antonio",
    state: "TX",
    zip: "78218",
    phone: "(210) 555-1967",
    email: "repair@alamocityglass.com",
    hasWebsite: false,
    googlePlaceId: "gp_020",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "NEW",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    contactEvents: [],
    notes: [],
  },
  {
    id: "lead_007",
    businessName: "Luxe Salon & Spa",
    address: "2222 Rio Grande St",
    city: "Austin",
    state: "TX",
    zip: "78705",
    phone: "(512) 555-0614",
    email: "hello@luxesalonspa.com",
    hasWebsite: false,
    googlePlaceId: "gp_007",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "NEW",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    contactEvents: [],
    notes: [],
  },
  {
    id: "lead_008",
    businessName: "River Oaks Cleaning Co",
    address: "1919 Westheimer Rd",
    city: "Houston",
    state: "TX",
    zip: "77098",
    phone: "(713) 555-1124",
    email: "info@riveroakscleaning.com",
    hasWebsite: false,
    googlePlaceId: "gp_012",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "FOLLOW_UP",
    lastContactedAt: daysAgo(4),
    nextFollowUpAt: daysFromNow(0),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(4),
    contactEvents: [
      {
        id: "ce_009",
        leadId: "lead_008",
        type: "EMAIL",
        notes: "Cold email sent. Got a reply asking for pricing.",
        outcome: "Interested in pricing",
        createdAt: daysAgo(4),
      },
    ],
    notes: [
      {
        id: "note_004",
        leadId: "lead_008",
        content: "They want a booking/quote form on the site. Budget is flexible — follow up today.",
        createdAt: daysAgo(4),
        updatedAt: daysAgo(4),
      },
    ],
  },
  {
    id: "lead_009",
    businessName: "Brisket & Beans BBQ",
    address: "4501 San Jacinto St",
    city: "Houston",
    state: "TX",
    zip: "77004",
    phone: "(713) 555-0923",
    email: "orders@brisketandbeans.com",
    hasWebsite: false,
    googlePlaceId: "gp_010",
    closeabilityScore: 90,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 20, bothContacts: 10, noContacts: 0 },
    status: "SAVED",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    contactEvents: [],
    notes: [],
  },
  {
    id: "lead_010",
    businessName: "Magnolia Roofing & Gutters",
    address: "14200 N Interstate 35",
    city: "Austin",
    state: "TX",
    zip: "78728",
    phone: "(512) 555-0789",
    hasWebsite: false,
    googlePlaceId: "gp_008",
    closeabilityScore: 60,
    scoreBreakdown: { noWebsite: 40, hasPhone: 20, hasEmail: 0, bothContacts: 0, noContacts: 0 },
    status: "SAVED",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    contactEvents: [],
    notes: [],
  },
]

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalSaved: MOCK_SAVED_LEADS.length,
  newThisWeek: MOCK_SAVED_LEADS.filter(
    (l) => new Date(l.createdAt) > new Date(now - 7 * 86400000)
  ).length,
  withoutWebsites: MOCK_SAVED_LEADS.filter((l) => !l.hasWebsite).length,
  followUpsDue: MOCK_SAVED_LEADS.filter(
    (l) => l.nextFollowUpAt && new Date(l.nextFollowUpAt) <= new Date(now + 86400000)
  ).length,
  activePipeline: MOCK_SAVED_LEADS.filter((l) =>
    ["INTERESTED", "FOLLOW_UP", "CONTACTED"].includes(l.status)
  ).length,
  wonThisMonth: MOCK_SAVED_LEADS.filter(
    (l) => l.status === "WON" && new Date(l.updatedAt) > new Date(now - 30 * 86400000)
  ).length,
}

export const MOCK_STATUS_COUNTS: StatusCount[] = (
  [
    { status: "NEW" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "NEW").length },
    { status: "SAVED" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "SAVED").length },
    { status: "CONTACTED" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "CONTACTED").length },
    { status: "FOLLOW_UP" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "FOLLOW_UP").length },
    { status: "INTERESTED" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "INTERESTED").length },
    { status: "NOT_INTERESTED" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "NOT_INTERESTED").length },
    { status: "WON" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "WON").length },
    { status: "LOST" as const, count: MOCK_SAVED_LEADS.filter((l) => l.status === "LOST").length },
  ] satisfies StatusCount[]
).filter((s) => s.count > 0)

export const MOCK_RECENT_ACTIVITY = [
  ...MOCK_SAVED_LEADS.flatMap((lead) =>
    (lead.contactEvents ?? []).map((ce) => ({ type: "contact" as const, lead, event: ce }))
  ),
  ...MOCK_SAVED_LEADS.filter((l) =>
    new Date(l.createdAt) > new Date(now - 7 * 86400000)
  ).map((lead) => ({ type: "saved" as const, lead, event: null })),
]
  .sort((a, b) => {
    const dateA = a.event ? a.event.createdAt : a.lead.createdAt
    const dateB = b.event ? b.event.createdAt : b.lead.createdAt
    return new Date(dateB).getTime() - new Date(dateA).getTime()
  })
  .slice(0, 8)
